# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3d6e3ef9010551de935190cf133f2b64b7531da7dc7a4ace6dec9bb4a41f53ca71951443e63ec351b9aa23ca2b13211e2bc0817435ed8af04faa3c8418e8f76

test:
  secret_key_base: e6dc1cc60376277d58e918fb3929d5e1c7ed75dfc8f75b31deba057422219ba397d6259edfb11e3d2bae274dfe4318c54e0940e02d5b77df99984d16dc0c0b21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
